climates = {
    # 🌾 Tamil Nadu Districts
    "chennai": "tropical savanna (Aw)",
    "chengalpattu": "tropical savanna (Aw)",
    "kancheepuram": "tropical savanna (Aw)",
    "tiruvallur": "tropical humid",
    "vellore": "tropical savanna",
    "ranipet": "tropical savanna",
    "tiruvannamalai": "semi-arid / dry tropical",
    "krishnagiri": "tropical dry",
    "dharmapuri": "tropical dry semi-arid",
    "salem": "tropical semi-arid",
    "namakkal": "tropical semi-arid",
    "villupuram": "tropical wet/dry",
    "cuddalore": "tropical humid",
    "perambalur": "tropical humid",
    "ariyalur": "tropical humid",
    "tiruchirappalli": "tropical semi-arid",
    "thanjavur": "tropical monsoon",
    "tiruvarur": "tropical monsoon",
    "nagapattinam": "tropical coastal",
    "mayiladuthurai": "tropical coastal",
    "madurai": "tropical dry-wet mix",
    "dindigul": "subtropical dry to temperate",
    "karur": "tropical semi-arid",
    "theni": "temperate / montane",
    "sivaganga": "semi-arid",
    "ramanathapuram": "arid coastal",
    "virudhunagar": "arid / semi-arid",
    "thoothukudi": "dry / arid",
    "tirunelveli": "tropical semi-arid",
    "tenkasi": "tropical humid/temperate",
    "kanniyakumari": "tropical rainforest (Af)",
    "coimbatore": "tropical semi-arid (rain shadow)",
    "tiruppur": "tropical semi-arid",
    "erode": "tropical semi-arid",
    "nilgiris": "temperate highland (Cwb)",

    # 🇮🇳 Major Indian Cities
    "mumbai": "tropical wet and dry (Aw)",
    "delhi": "humid subtropical (Cwa)",
    "bangalore": "tropical savanna (Aw)",
    "hyderabad": "tropical semi-arid",
    "kolkata": "humid subtropical (Cwa)",
    "ahmedabad": "tropical monsoon",
    "jaipur": "hot semi-arid (BSh)",
    "lucknow": "humid subtropical (Cwa)",
    "bhopal": "humid subtropical",
    "indore": "tropical savanna",
    "pune": "tropical wet and dry",
    "nagpur": "tropical wet and dry",
    "visakhapatnam": "tropical savanna",
    "kochi": "tropical monsoon (Am)",
    "bhubaneswar": "tropical wet and dry",
    "trivandrum": "tropical monsoon",
    "patna": "humid subtropical",
    "ranchi": "humid subtropical",
    "dehradun": "humid subtropical (Cwa)",
    "shimla": "subtropical highland (Cwb)",
    "srinagar": "humid continental (Dfb)",
    "guwahati": "humid subtropical",
    "imphal": "subtropical",
    "panaji": "tropical monsoon (Am)",
    "gangtok": "subtropical highland (Cwb)"
}
